import Link from "next/link";
import { ShieldCheck, Package, Lock } from "lucide-react";
import prisma from "@/lib/prisma";
import { CheckoutButton } from "./CheckoutButton";

// Simulated immutable license snapshot (INV-004)
const MOCK_LICENSE_SNAPSHOT = {
  designTitle: "Whispering Bamboo",
  designVersion: "v2",
  licenseType: "PERSONAL_PRODUCT",
  priceAtPurchase: "$31.99",
  permissions: {
    allowName: true,
    allowQuote: true,
    allowTranslation: true,
    allowCalligraphy: true,
    allowAIRestyle: false,
    allowCommercial: false,
    allowModelTraining: false,
  },
};

const RETAIL_TARGET_PRICES: Record<string, number> = {
  "Premium Hoodie": 99.00,
  "Classic T-Shirt": 45.00,
  "Canvas Print": 49.00,
  "Tote Bag": 29.00,
  "Coffee Mug": 19.00,
  "Poster": 25.00,
};

export default async function CheckoutPage({ searchParams }: { searchParams: Promise<{ candidate?: string, product?: string }> }) {
  const params = await searchParams;
  const candidateId = params.candidate;
  const productId = params.product || "Premium Hoodie";

  let calligraphyData = null;
  
  if (candidateId) {
    const candidate = await prisma.generatedDesignVariation.findUnique({
      where: { id: candidateId },
      include: {
        generatedDesign: {
          include: {
            phraseKnowledge: true
          }
        }
      }
    });

    if (candidate) {
      calligraphyData = {
        sessionId: "00000000-0000-0000-0000-000000000000",
        candidateId: candidate.id,
        imageUrl: candidate.assetId,
        inputText: candidate.generatedDesign.phraseKnowledge.displayInput,
        interpretation: candidate.generatedDesign.phraseKnowledge.interpretationType,
        interpretedText: candidate.generatedDesign.phraseKnowledge.renderedText,
        romanization: candidate.generatedDesign.phraseKnowledge.romanization || "",
        meaning: candidate.generatedDesign.phraseKnowledge.meaning || "Original text",
        culturalNote: "Generated by Cultural Intelligence Engine.",
      };
    }
  }

  // Fallback to mock data if candidate wasn't found or URL was visited directly
  if (!calligraphyData) {
    calligraphyData = {
      sessionId: "00000000-0000-0000-0000-000000000000",
      candidateId: "mock-candidate-123",
      imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDA-xqdAr5uF8q7H2XYGhT6BxFjLjWe-1669EcvwFCPiTr9gFVtnzc_BSmRmq0_sngcI867AcXOqrFKBz_EpttmTdRgHANT4YNsjtaqfibOQ9IlKn7nR1VRdd6Wg7g2-8rUunhJ0QcV-NDwyBACOqZR7eFJu-SlskItrkE-J5SyZUQQ_wpI9xzkcgS6xFoiDq5dHBJsCWXePnLba63MwEoTYE5a2NfeeR_JCNzw84vAh0X0LSmjWYf2",
      inputText: "Never Give Up",
      interpretation: "Idiomatic",
      interpretedText: "七転八起",
      romanization: "Shichitenhakki",
      meaning: "Fall seven times, stand up eight",
      culturalNote: "A classic Yojijukugo (four-character idiom). Embodies the Zen spirit of resilience and unyielding perseverance.",
    };
  }

  let items: { label: string, amount: string }[] = [];
  let totalPrice = 0;

  if (productId === "Digital Download (All 6)") {
    items = [
      { label: "Artwork License", amount: "$4.99" },
      { label: "AI Personalization", amount: "$2.00" },
      { label: "High-Res Digital Export (All 6 Variations)", amount: "$3.00" },
    ];
    totalPrice = 9.99;
  } else {
    const targetRetail = RETAIL_TARGET_PRICES[productId] || 45.00;
    // The target retail price INCLUDES the artwork and AI fees.
    const productCharge = targetRetail - 4.99 - 2.00;
    
    items = [
      { label: "Artwork License", amount: "$4.99" },
      { label: "AI Personalization", amount: "$2.00" },
      { label: `${productId} Base`, amount: `$${productCharge.toFixed(2)}` },
    ];
    totalPrice = targetRetail;
  }

  return (
    <div className="bg-background text-on-background min-h-screen flex flex-col font-body-md antialiased">
      <main className="flex-grow w-full max-w-container-max mx-auto px-margin-mobile md:px-margin-desktop py-12 flex flex-col gap-12">
        {/* Header */}
        <header className="border-b border-surface-variant pb-6">
          <h1 className="font-display-lg-mobile md:font-display-lg text-display-lg-mobile md:text-display-lg text-on-background">Secure Checkout</h1>
          <p className="font-body-md text-body-md text-on-surface-variant mt-2">Review your personalized artwork and complete your order.</p>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
          {/* LEFT — Order Summary + License Snapshot */}
          <div className="lg:col-span-7 flex flex-col gap-8">

            {/* License Snapshot Card (INV-003 + INV-004) */}
            <section className="border border-surface-variant bg-surface-container-lowest p-8 flex flex-col gap-6">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <h2 className="font-headline-sm text-headline-sm text-on-background">{MOCK_LICENSE_SNAPSHOT.designTitle}</h2>
                  <p className="font-label-caps text-label-caps text-on-surface-variant mt-1 uppercase">
                    Design {MOCK_LICENSE_SNAPSHOT.designVersion} · {MOCK_LICENSE_SNAPSHOT.licenseType.replace("_", " ")} License
                  </p>
                </div>
                <div className="flex items-center gap-1 text-on-surface-variant">
                  <Lock className="w-4 h-4" />
                  <span className="font-label-caps text-label-caps text-[10px] uppercase">Immutable Snapshot</span>
                </div>
              </div>

              {/* Calligraphy Semantic Breakdown (INV-011) */}
              <div className="border-t border-surface-variant pt-6">
                <h3 className="font-label-caps text-label-caps text-on-surface-variant uppercase mb-4 border-b border-surface-variant pb-2">Cultural Meaning</h3>
                <div className="flex gap-6 items-start">
                  <div className="text-center bg-surface-container-low p-6 flex items-center justify-center min-h-[120px] min-w-[120px]">
                    <span className="text-5xl text-on-background leading-none" style={{ fontFamily: "'Noto Serif JP', serif" }}>
                      {calligraphyData.interpretedText}
                    </span>
                  </div>
                  <div className="flex flex-col gap-2">
                    <p className="font-body-md text-body-md text-on-surface-variant">
                      Your phrase: <span className="text-on-background font-medium">&ldquo;{calligraphyData.inputText}&rdquo;</span>
                    </p>
                    <p className="font-body-md text-body-md text-on-surface-variant">
                      Interpretation: <span className="text-on-background font-medium">{calligraphyData.interpretation}</span>
                    </p>
                    <p className="font-body-md text-body-md text-on-surface-variant">
                      Romanization: <span className="text-on-background font-medium">{calligraphyData.romanization}</span>
                    </p>
                    <p className="font-body-md text-body-md text-on-surface-variant italic">&ldquo;{calligraphyData.meaning}&rdquo;</p>
                    <p className="font-label-caps text-label-caps text-on-surface-variant text-[11px] mt-2">{calligraphyData.culturalNote}</p>
                  </div>
                </div>
              </div>

              {/* License Permissions Grid (INV-004 snapshot) */}
              <div className="border-t border-surface-variant pt-6">
                <h3 className="font-label-caps text-label-caps text-on-surface-variant uppercase mb-4">License Permissions (Frozen)</h3>
                <div className="grid grid-cols-2 gap-2">
                  {Object.entries(MOCK_LICENSE_SNAPSHOT.permissions).map(([key, allowed]) => (
                    <div key={key} className="flex items-center gap-2">
                      <div className={`w-3 h-3 rounded-full flex-shrink-0 ${allowed ? 'bg-primary' : 'bg-surface-container-highest'}`} />
                      <span className={`font-label-caps text-label-caps uppercase text-[11px] ${allowed ? 'text-on-background' : 'text-outline'}`}>
                        {key.replace(/allow/g, "").replace(/([A-Z])/g, " $1").trim()}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            </section>

            {/* Product Summary */}
            <section className="border border-surface-variant bg-surface-container-lowest p-6">
              <h2 className="font-headline-sm text-headline-sm text-on-background mb-4">Product</h2>
              <div className="flex items-start gap-4">
                <div className="w-32 h-32 bg-white border border-surface-variant overflow-hidden flex-shrink-0 p-2">
                  <img
                    src={calligraphyData.imageUrl}
                    alt="Product preview"
                    className="w-full h-full object-contain mix-blend-multiply"
                  />
                </div>
                <div className="flex flex-col gap-1">
                  <p className="font-body-md text-body-md font-medium text-on-background">{productId}</p>
                  <p className="font-label-caps text-label-caps text-on-surface-variant">Size: L · Color: Bone White</p>
                  <p className="font-label-caps text-label-caps text-on-surface-variant">Qty: 1</p>
                </div>
              </div>
            </section>
          </div>

          {/* RIGHT — Payment Panel */}
          <div className="lg:col-span-5 flex flex-col gap-6">
            {/* Price Breakdown */}
            <section className="border border-surface-variant bg-surface-container-lowest p-6 flex flex-col gap-4">
              <h2 className="font-headline-sm text-headline-sm text-on-background">Order Summary</h2>
              <div className="flex flex-col gap-3 border-b border-surface-variant pb-4">
                {items.map((item) => (
                  <div key={item.label} className="flex justify-between items-center">
                    <span className="font-body-md text-body-md text-on-surface-variant">{item.label}</span>
                    <span className="font-body-md text-body-md text-on-background">{item.amount}</span>
                  </div>
                ))}
              </div>
              <div className="flex justify-between items-center">
                <span className="font-headline-sm text-headline-sm text-on-background">Total</span>
                <span className="font-headline-sm text-headline-sm text-on-background">${totalPrice.toFixed(2)}</span>
              </div>
            </section>

            {/* Express Payment */}
            <section className="flex flex-col gap-3">
              <CheckoutButton 
                sessionId={calligraphyData.sessionId} 
                candidateId={calligraphyData.candidateId} 
                productId={productId} 
              />
              <button className="w-full border border-outline-variant py-4 font-label-caps text-label-caps uppercase flex items-center justify-center gap-2 text-on-background hover:bg-surface-container-low transition-colors">
                <Package className="w-5 h-5" />
                Apple Pay
              </button>
            </section>

            {/* Trust Signals */}
            <div className="flex items-center justify-center gap-2 text-on-surface-variant">
              <ShieldCheck className="w-4 h-4" />
              <span className="font-label-caps text-label-caps text-[11px] uppercase">Secure Checkout · Stripe Encrypted</span>
            </div>

            <p className="font-label-caps text-label-caps text-[11px] text-on-surface-variant text-center leading-relaxed">
              By completing this purchase, you agree to the license terms shown above. The design snapshot and permissions are permanently recorded and cannot be changed after purchase.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
