import { fal } from "@fal-ai/client";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export class BackgroundGenerationService {
  /**
   * Generates a background using Fal.ai Flux based on a preset and user options.
   */
  static async generatePresetBackground(options: {
    presetKey: string;
    mood?: string;
    palette?: string;
    intensity?: string;
    userNote?: string;
    compositionId?: string;
  }) {
    try {
      let preset: any = null;
      if (prisma.backgroundPreset) {
        preset = await prisma.backgroundPreset.findUnique({
          where: { key: options.presetKey },
        });
      } else {
        const records: any[] = await prisma.$queryRaw`
          SELECT * FROM "BackgroundPreset" WHERE "key" = ${options.presetKey} LIMIT 1
        `;
        preset = records[0] || null;
      }

      if (!preset) {
        throw new Error(`Preset ${options.presetKey} not found`);
      }

      const mood = options.mood || preset.defaultMood || "Calm";
      const palette = options.palette || preset.defaultPalette || "Neutral";
      const intensity = options.intensity || preset.defaultIntensity || "Medium";
      
      let prompt = preset.promptTemplate
        .replace("{{mood}}", mood)
        .replace("{{palette}}", palette)
        .replace("{{intensity}}", intensity);

      if (options.userNote) {
        prompt = prompt.replace("{{userNote}}", `Additional note: ${options.userNote}`);
      } else {
        prompt = prompt.replace("{{userNote}}", "");
      }

      // Generate via Fal.ai Flux
      // Assuming model `fal-ai/flux/schnell` for fast generations
      const result: any = await fal.subscribe("fal-ai/flux/schnell", {
        input: {
          prompt: prompt,
          image_size: "portrait_4_3", // Standard aspect ratio for print
          num_inference_steps: 4,
          num_images: 1,
          enable_safety_checker: true
        },
        logs: true,
        onQueueUpdate: (update: any) => {
          if (update.status === "IN_PROGRESS") {
            console.log(update.logs);
          }
        },
      });

      if (!result.images || result.images.length === 0) {
        throw new Error("No image generated by Fal.ai");
      }

      const imageUrl = result.images[0].url;

      return {
        url: imageUrl,
        promptUsed: prompt,
        success: true,
      };
    } catch (error: any) {
      console.error("Background generation error:", error);
      return {
        url: null,
        success: false,
        error: error.message,
      };
    }
  }
}
